version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.17.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}

      - run: yarn test
